In [3]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

In [17]:
pd_data = pd.read_csv(Path.cwd() /'data'/'AB_NYC_2019.csv', index_col=0)
print("Data Shape: ", pd_data.shape)
pd_data.head()

Data Shape:  (48895, 15)

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
id,,,,,,,,,,,,,,,
2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [32]:
first_ten_rows = pd_data.head(10).copy() # We added the copy method because "pd_data.head(10)" only creates a view, and any modification on it, affcet s the main data. 
first_ten_rows

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
id,,,,,,,,,,,,,,,
2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,1,129
5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,45,49,2017-10-05,0.40,1,0
5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,79,2,430,2019-06-24,3.47,1,220
5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,79,2,118,2017-07-21,0.99,1,0
5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.71344,-73.99037,Entire home/apt,150,1,160,2019-06-09,1.33,4,188

In [34]:
# Normal iteration 
for label, row in first_ten_rows.iterrows():
    print("label :", label) #This prints out the index column value
    print("row: ", row)     # This prints out the column name and column value for the corresponding index value.

label : 2539
row:  name                              Clean & quiet apt home by the park
host_id                                                         2787
host_name                                                       John
neighbourhood_group                                         Brooklyn
neighbourhood                                             Kensington
latitude                                                    40.64749
longitude                                                  -73.97237
room_type                                               Private room
price                                                            149
minimum_nights                                                     1
number_of_reviews                                                  9
last_review                                               2018-10-19
reviews_per_month                                               0.21
calculated_host_listings_count                                     6
availability_365                                                 365
Name: 2539, dtype: object
label : 2595
row:  name                              Skylit Midtown Castle
host_id                                            2845
host_name                                      Jennifer
neighbourhood_group                           Manhattan
neighbourhood                                   Midtown
latitude                                       40.75362
longitude                                     -73.98377
room_type                               Entire home/apt
price                                               225
minimum_nights                                        1
number_of_reviews                                    45
last_review                                  2019-05-21
reviews_per_month                                  0.38
calculated_host_listings_count                        2
availability_365                                    355
Name: 2595, dtype: object
label : 3647
row:  name                              THE VILLAGE OF HARLEM....NEW YORK !
host_id                                                          4632
host_name                                                   Elisabeth
neighbourhood_group                                         Manhattan
neighbourhood                                                  Harlem
latitude                                                     40.80902
longitude                                                    -73.9419
room_type                                                Private room
price                                                             150
minimum_nights                                                      3
number_of_reviews                                                   0
last_review                                                       NaN
reviews_per_month                                                 NaN
calculated_host_listings_count                                      1
availability_365                                                  365
Name: 3647, dtype: object
label : 3831
row:  name                              Cozy Entire Floor of Brownstone
host_id                                                      4869
host_name                                             LisaRoxanne
neighbourhood_group                                      Brooklyn
neighbourhood                                        Clinton Hill
latitude                                                 40.68514
longitude                                               -73.95976
room_type                                         Entire home/apt
price                                                          89
minimum_nights                                                  1
number_of_reviews                                             270
last_review                                            2019-07-05
reviews_per_month                                            4.64
calculated_host_listings_count                                  1
availability_365                                              194
Name: 3831, dtype: object
label : 5022
row:  name                              Entire Apt: Spacious Studio/Loft by central park
host_id                                                                       7192
host_name                                                                    Laura
neighbourhood_group                                                      Manhattan
neighbourhood                                                          East Harlem
latitude                                                                  40.79851
longitude                                                                -73.94399
room_type                                                          Entire home/apt
price                                                                           80
minimum_nights                                                                  10
number_of_reviews                                                                9
last_review                                                             2018-11-19
reviews_per_month                                                              0.1
calculated_host_listings_count                                                   1
availability_365                                                                 0
Name: 5022, dtype: object
label : 5099
row:  name                              Large Cozy 1 BR Apartment In Midtown East
host_id                                                                7322
host_name                                                             Chris
neighbourhood_group                                               Manhattan
neighbourhood                                                   Murray Hill
latitude                                                           40.74767
longitude                                                           -73.975
room_type                                                   Entire home/apt
price                                                                   200
minimum_nights                                                            3
number_of_reviews                                                        74
last_review                                                      2019-06-22
reviews_per_month                                                      0.59
calculated_host_listings_count                                            1
availability_365                                                        129
Name: 5099, dtype: object
label : 5121
row:  name                                 BlissArtsSpace!
host_id                                         7356
host_name                                      Garon
neighbourhood_group                         Brooklyn
neighbourhood                     Bedford-Stuyvesant
latitude                                    40.68688
longitude                                  -73.95596
room_type                               Private room
price                                             60
minimum_nights                                    45
number_of_reviews                                 49
last_review                               2017-10-05
reviews_per_month                                0.4
calculated_host_listings_count                     1
availability_365                                   0
Name: 5121, dtype: object
label : 5178
row:  name                              Large Furnished Room Near B'way
host_id                                                       8967
host_name                                                 Shunichi
neighbourhood_group                                      Manhattan
neighbourhood                                       Hell's Kitchen
latitude                                                  40.76489
longitude                                                -73.98493
room_type                                             Private room
price                                                           79
minimum_nights                                                   2
number_of_reviews                                              430
last_review                                             2019-06-24
reviews_per_month                                             3.47
calculated_host_listings_count                                   1
availability_365                                               220
Name: 5178, dtype: object
label : 5203
row:  name                              Cozy Clean Guest Room - Family Apt
host_id                                                         7490
host_name                                                  MaryEllen
neighbourhood_group                                        Manhattan
neighbourhood                                        Upper West Side
latitude                                                    40.80178
longitude                                                  -73.96723
room_type                                               Private room
price                                                             79
minimum_nights                                                     2
number_of_reviews                                                118
last_review                                               2017-07-21
reviews_per_month                                               0.99
calculated_host_listings_count                                     1
availability_365                                                   0
Name: 5203, dtype: object
label : 5238
row:  name                              Cute & Cozy Lower East Side 1 bdrm
host_id                                                         7549
host_name                                                        Ben
neighbourhood_group                                        Manhattan
neighbourhood                                              Chinatown
latitude                                                    40.71344
longitude                                                  -73.99037
room_type                                            Entire home/apt
price                                                            150
minimum_nights                                                     1
number_of_reviews                                                160
last_review                                               2019-06-09
reviews_per_month                                               1.33
calculated_host_listings_count                                     4
availability_365                                                 188
Name: 5238, dtype: object

In [36]:
for label, row in first_ten_rows.iterrows():
    print(f"{label} :", row["host_name"])   #Prints only the value of the host_name column for each row

2539 : John
2595 : Jennifer
3647 : Elisabeth
3831 : LisaRoxanne
5022 : Laura
5099 : Chris
5121 : Garon
5178 : Shunichi
5203 : MaryEllen
5238 : Ben

#### Adding new columns
A more efficient way to add new columns to an existing Dataframe is to use the apply() method.
**apply()** method also accepts a call back function, which is called on every iteration. The return value of the function is assigned a the value for the new column.

In [28]:
def price_2024(old_price):
    return old_price * 1.25

In [38]:
first_ten_rows['2024_price'] = first_ten_rows['price'].apply(price_2024)
first_ten_rows

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,2024_price
id,,,,,,,,,,,,,,,,
2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365,186.25
2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355,281.25
3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365,187.50
3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194,111.25
5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0,100.00
5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,1,129,250.00
5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,45,49,2017-10-05,0.40,1,0,75.00
5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,79,2,430,2019-06-24,3.47,1,220,98.75
5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,79,2,118,2017-07-21,0.99,1,0,98.75
5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.71344,-73.99037,Entire home/apt,150,1,160,2019-06-09,1.33,4,188,187.50